# Generated by Django 5.2.17 on 2026-09-02 04:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons_possedees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('identifiant_appareil', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('statut_appairage', models.CharField(choices=[('unpaired', 'Non appairée'), ('paired', 'Appairée'), ('revoked', 'Révoquée')], default='unpaired', max_length=12)),
                ('surveillance_active', models.BooleanField(default=False)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='homes.maison')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='MembreMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('family', 'Membre de la famille'), ('guest', 'Invité')], default='guest', max_length=12)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], default='pending', max_length=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='homes.maison')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions_maison', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maison',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='maisons', through='homes.MembreMaison', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccesCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_voir', models.BooleanField(default=True)),
                ('peut_controler', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='homes.camera')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_cameras', to='homes.membremaison')),
            ],
        ),
        migrations.AddConstraint(
            model_name='membremaison',
            constraint=models.UniqueConstraint(fields=('maison', 'utilisateur'), name='unique_membre_maison'),
        ),
        migrations.AddConstraint(
            model_name='accescamera',
            constraint=models.UniqueConstraint(fields=('membre', 'camera'), name='unique_acces_camera'),
        ),
    ]
