# Generated by Django 5.2.17 on 2026-09-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='date_appairage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='secret_appareil_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='camera',
            name='version_jeton',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CodeAppairage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('nom_prevu_camera', models.CharField(max_length=120)),
                ('date_expiration', models.DateTimeField(db_index=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('utilise', models.BooleanField(db_index=True, default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_appairage', to='homes.camera')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_appairage', to='homes.maison')),
            ],
            options={
                'ordering': ('-date_creation',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date_utilisation__isnull', True), ('utilise', False)), models.Q(('date_utilisation__isnull', False), ('utilise', True)), _connector='OR'), name='pairing_use_date_consistent')],
            },
        ),
    ]
