# Generated by Django 5.2.17 on 2026-09-02 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_camera_date_appairage_camera_secret_appareil_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.UUIDField(editable=False, unique=True)),
                ('type', models.CharField(choices=[('person_detected', 'Personne détectée'), ('simulation', 'Détection simulée')], max_length=24)),
                ('confiance_ia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('statut', models.CharField(choices=[('new', 'Nouveau'), ('false_alarm', 'Fausse alerte'), ('confirmed', 'Intrusion confirmée')], default='new', max_length=16)),
                ('simule', models.BooleanField(default=False)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='homes.camera')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='homes.maison')),
            ],
            options={
                'ordering': ('-horodatage',),
            },
        ),
        migrations.CreateModel(
            name='CaptureChiffree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_chiffre', models.BinaryField()),
                ('nonce', models.BinaryField(max_length=12)),
                ('type_mime', models.CharField(max_length=32)),
                ('taille', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture', to='homes.evenement')),
            ],
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['maison', '-horodatage'], name='event_house_time_idx'),
        ),
    ]
