# Generated by Django 5.2.17 on 2026-09-02 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_evenement_capturechiffree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cle_signature_evenement_chiffree',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='nonce_cle_signature_evenement',
            field=models.BinaryField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='NonceRequeteCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(editable=False, unique=True)),
                ('horodatage_client', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces_requetes', to='homes.camera')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('resultat', models.CharField(choices=[('success', 'Succès'), ('denied', 'Refus'), ('failure', 'Échec')], max_length=12)),
                ('type_acteur', models.CharField(choices=[('user', 'Utilisateur'), ('camera', 'Caméra'), ('anonymous', 'Anonyme'), ('system', 'Système')], max_length=12)),
                ('cible_type', models.CharField(blank=True, max_length=40)),
                ('cible_id', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to='homes.camera')),
                ('maison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to='homes.maison')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_creation',),
                'indexes': [models.Index(fields=['action', '-date_creation'], name='audit_action_time_idx'), models.Index(fields=['camera', '-date_creation'], name='audit_camera_time_idx')],
            },
        ),
    ]
